name: LED Blink

on:
  push:
    branches:
      - master
jobs:
  test:
      name: Run tests
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.x"]
  
      steps:
        - name: Python Action
          uses: jge162/Action-workflows@2.1.0
    
        - run: |
            echo "Install required dependencies" 
            sudo apt-get update
            sudo apt-get install python3    
        
            # Lastly use a `for` loop to run multiple instances of Python scripts.
            # This way you can run one, or multiple python scripts.
    
        - run: |
            echo "Run, Build Application using scripts"
            python3 -c "
            scripts = ['./control_led.py']
            with open(script, 'r') as file:
                exec(file.read())"
  build:
    needs: test  # Specify that "build" depends on "test" job
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm/v7
        push: true
        tags: putraarengga/ci:latest
